common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='index'),  # <a href="{% url 'index' %}">Home</a>.
    path('places/', views.PlaceListView.as_view(), name='places'),
    path('place/<int:pk>', views.PlaceDetailView.as_view(), name='place-detail'),
    path('suggest/', views.SuggestionView.as_view(), name='suggest-place'),
    path('suggest_data/', views.SuggestionViewData.as_view(), name='suggest-data'),
    path('user_place_data/', views.UserPlaceData.as_view(), name='user-place-data'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('export/', views.export, name='export'),
]

foodmates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('', RedirectView.as_view(url='/common/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

common/models.py
from django.utils import timezone

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from common import choices


class Vote(models.Model):
    profile = models.ForeignKey("Profile",
                                related_name="profile_votes",
                                null=True, on_delete=models.SET_NULL)
    place = models.ForeignKey("Place",
                              related_name="place_votes",
                              null=True, on_delete=models.CASCADE)
    rate = models.PositiveSmallIntegerField()
    vote_datetime = models.DateTimeField(auto_now_add=timezone.now)

    class Meta:
        ordering = ['-rate']

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.profile.user.first_name + ": " + str(self.rate)


class Place(models.Model):
    """
    Model representing a place where people can lunch.
    """

    title = models.CharField(max_length=64,
                             help_text="Enter a place title (e.g. Orhan Aspava, Dolmacı etc.")
    description = models.TextField(blank=True, null=True)
    rate = models.FloatField()

    class Meta:
        ordering = ['-rate']

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('common:place-detail', args=[str(self.id)])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    location = models.CharField(max_length=30, blank=True)
    age = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.user.first_name

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()


class Condition(models.Model):
    pay = models.IntegerField(choices=choices.PAY_CHOICES)
    time = models.IntegerField(choices=choices.TIME_CHOICES)
    kitchen = models.IntegerField(choices=choices.KITCHEN_CHOICES)
    hunger = models.IntegerField(choices=choices.HUNGER_CHOICES)

    profile = models.ForeignKey("Profile",
                                related_name="profile_conds",
                                null=True, on_delete=models.SET_NULL)

    place = models.ForeignKey(Place, on_delete=models.CASCADE)

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """

        return '{} {} {} {} {}'.format(self.pay, self.time, self.kitchen, self.hunger, self.place.id)

common/forms.py
from crispy_forms.layout import Layout, Field
from django import forms
from crispy_forms.helper import FormHelper

from common.models import Vote, Condition, Place
from common import choices

class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'custom-select'


class VoteForm(forms.Form):
    your_vote = forms.FloatField(required=True, max_value=10, min_value=0,label='',
                                 widget=forms.NumberInput(
                                     attrs={'id': 'your_vote', 'step': "1.00"}))
    your_vote.widget.attrs['class'] = 'form-control vote-form'
    your_vote.widget.attrs['placeholder'] = "Your vote..."

    def clean_your_vote(self):
        data = self.cleaned_data['your_vote']
        return data

    class Meta:
        model = Vote
        fields = ('vote',)


class ConditionForm(BaseForm):

    pay = forms.ChoiceField(choices=choices.PAY_CHOICES)
    time = forms.ChoiceField(choices=choices.TIME_CHOICES)
    kitchen = forms.ChoiceField(choices=choices.KITCHEN_CHOICES)
    hunger = forms.ChoiceField(choices=choices.HUNGER_CHOICES)


    class Meta:
        model = Condition
        fields = ('pay', 'time', 'kitchen', 'hunger')

common/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from common import decisiontree, choices
from common.resources import ConditionResource
from django.views import generic, View
from common.forms import VoteForm, ConditionForm
from common.models import Place, Vote, Profile, Condition
import common.recommender as recommender


# MentalHealthError: an exception occurred.

def index(request):

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Generate counts of some of the main objects
    num_places = Place.objects.all().count()
    num_users = User.objects.count()

    context = {
        'num_users': num_users,
        'num_places': num_places,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'common/index.html', context=context)


class UserPlaceData(View):

    def get(self, request, *args, **kwargs):

        place_freq = {}

        for c in Condition.objects.all():
            if request.user.id == c.profile.user.id:
                title = Place.objects.get(id=c.place_id).title
                if place_freq.__contains__(title):
                    place_freq[title] += 1
                else:
                    place_freq[title] = 1

        labels = list(place_freq.keys())
        default_items = list(place_freq.values())

        data = {
            "labels": labels,
            "default": default_items,
        }

        return JsonResponse(data)


class PlaceListView(generic.ListView):
    model = Place
    paginate_by = 10
    context_object_name = 'place_list'
    template_name = 'common/place_list.html'

    def get_queryset(self):
        return Place.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(PlaceListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        # context['some'] = 'data'
        return context


class PlaceDetailView(View):

    def get(self, request, **kwargs):
        # from django.shortcuts import get_object_or_404
        place = get_object_or_404(Place, pk=kwargs.get('pk'))
        votes = list(place.place_votes.all().order_by('rate'))
        avg_rate = sum(vote.rate for vote in votes) / (len(votes) if votes else 1)
        if not avg_rate:
            avg_rate = place.rate

        place.rate = avg_rate
        place.save()
        vote_form = VoteForm()
        condition_form = ConditionForm

        return render(request, 'common/place_detail.html', context={'place': place,
                                                                    'vote_form': vote_form,
                                                                    'condition_form': condition_form})

    def post(self, request, **kwargs):

        # create a form instance and populate it with data from the request:
        vote_form = VoteForm(request.POST)
        condition_form = ConditionForm(request.POST)

        # check whether it's valid:
        if vote_form.is_valid():
            current_user = Profile.objects.get(user=request.user.id)
            place = get_object_or_404(Place, pk=kwargs.get('pk'))

            rate = vote_form.cleaned_data['your_vote']

            if condition_form.is_valid():
                cond = condition_form.save(commit=False)
                cond.place = place
                cond.profile = current_user
                print(cond)
                cond.save()
            vote, created = Vote.objects.update_or_create(profile=current_user,
                                                          place=place,
                                                          defaults={'profile': current_user,
                                                                    'place': place,
                                                                    'rate': rate})

            # redirect to a new URL:
            return HttpResponseRedirect(request.META['HTTP_REFERER'])

        return render(request, 'common/place_detail.html', {'vote_form': vote_form})


def export(request):
    person_resource = ConditionResource()
    dataset = person_resource.export()
    response = HttpResponse(dataset.json, content_type='text/json')
    response['Content-Disposition'] = 'attachment; filename="conditions.json"'
    return response


@method_decorator(csrf_exempt, name='dispatch')
class SuggestionView(View):
    success_url = '/'
    template_name = 'common/suggestion.html'

    def get(self, request, *args, **kwargs):
        users = Profile.objects.all()
        return render(request, self.template_name, {'users': users})

    def post(self, request):
        users = []
        conds = []

        for user_id in request.POST:
            user = User.objects.get(id=user_id)
            users.append(user)
            conds.append(user.profile.profile_conds.all())

        if len(users) == 0:
            message ='Invalid number of users. Please select at least one user to go to the lunch.'
            return render(request, 'common/ajax_data.html', context={'message': message,
                                                                     'place': 'NULL'
                                                                     })
        else:
            context = decisiontree.place_prediction(conds)
            if not context == -1:
                request.session['freq_dict'] = context['freq_dict']
                cond_info = self.get_cond_info(context['max_freq_conds'])
                request.session['cond_info'] = cond_info
                place_id = context['place_id']
                score = context['score']*100
                place = Place.objects.get(id=place_id)
                return render(request, 'common/ajax_data.html', context={'users': users,
                                                                         'place': place,
                                                                         'score': score,
                                                                         'cond_info': cond_info,
                                                                         'cond_count': context['total_cond_count']
                                                                         })
            else:
                message = 'No records found.'
                return render(request, 'common/ajax_data.html', context={'users': users,
                                                                         'place': 'NULL',
                                                                         'message': message
                                                                         })

    def get_cond_info(self, max_freq):
        print(max_freq)
        pay = (choices.PAY_CHOICES[max_freq[0]-1])[1]
        time = (choices.TIME_CHOICES[max_freq[1]-1])[1]
        kitchen = (choices.KITCHEN_CHOICES[max_freq[2]-1])[1]
        hunger = (choices.HUNGER_CHOICES[max_freq[3]-1])[1]

        cond_info = {'pay': pay,
                     'time': time,
                     'kitchen': kitchen,
                     'hunger': hunger}
        return cond_info


@method_decorator(csrf_exempt, name='dispatch')
class SuggestionViewData(View):

    def get(self, request, *args, **kwargs):

        freq = request.session.get('freq_dict')
        cond_info = request.session.get('cond_info')

        labels = [cond_info['pay'], cond_info['time'], cond_info['kitchen'], cond_info['hunger']]
        default_items = [freq['pay'], freq['time'], freq['kitchen'], freq['hunger']]
        data = {
            "labels": labels,
            "default": default_items,
        }

        return JsonResponse(data)


class ProfileView(View):

    def get(self, request, **kwargs):
        current_user = Profile.objects.get(user=request.user.id)
        cur_user_votes = current_user.profile_votes.all()

        recommender.read_database()
        recommended_places = recommender.find_knn(current_user.id)
        count = len(recommended_places)

        context = {
            'current_user': current_user,
            'recommended_places': recommended_places,
            'rec_places_count': count,
            'cur_user_votes': cur_user_votes,
        }

        return render(request, 'common/profile.html', context=context)

templates/common/ajax_data.html
{% if place == "NULL" %}
    <!-- Modal -->
    <div class="modal fade " id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content shadow-lg">

                <div class="modal-header">
                    <h4 class="modal-title" id="exampleModalLabel">Error message</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <p style="font-size:16px; font-family: 'Trebuchet MS'">{{ message }}</p>
                </div>
            </div>
        </div>
    </div>

{% else %}



    <div class="container" id="select-div">
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <div class="card border-light shadow-lg mb-3">
                    <h3 class="card-header">{{ place.title }}</h3>
                    <div class="card-body">
                        <h5 class="card-title">Avg. Rate: {{ place.rate|floatformat }}</h5>
                        <h6 class="card-subtitle text-muted">Kebab</h6>
                    </div>
                    <img style="height: 200px; width: 100%; display: block;"
                         src="https://images.pexels.com/photos/6267/menu-restaurant-vintage-table.jpg?auto=compress&cs=tinysrgb&h=350"
                         alt="Card image">
                    <div class="card-body">
                        <p class="card-text">{{ place.description }}</p>
                        <a href="{{ place.get_absolute_url }}" class="card-link">Restaurant link</a>
                    </div>
                    <div class="card-footer text-muted">
                        <button class="btn btn-outline-primary" onclick="myFunction()">Go Back</button>

                    </div>
                </div>
            </div>
            <div class="col col-lg-6">


                <div class="card shadow-lg mb-3">
                    <div class="card-header"><h4>Statistical Data</h4>
                        <h6 class="card-subtitle text-muted">Most popular condition</h6>
                    </div>

                    <div class="card-body">
                        <canvas id="myChart" height="40vh" width="80vw"></canvas>
                    </div>

                    <ul class="list-group list-group-flush">
                        <p style="font-size: 12px;"><i>according to the data obtained from <b>{{ cond_count }}</b>
                            conditions</i></p>
                        <li class="list-group-item"><strong>Pay: </strong>{{ cond_info.pay }}</li>
                        <li class="list-group-item"><strong>Time: </strong>{{ cond_info.time }}</li>
                        <li class="list-group-item"><strong>Kitchen: </strong>{{ cond_info.kitchen }}</li>
                        <li class="list-group-item"><strong>Hunger: </strong>{{ cond_info.hunger }}</li>

                    </ul>
                </div>
                <div class="card text-white bg-success mb-3">
                    <div class="card-header"><h4>Accuracy Score</h4></div>
                    <div class="card-body">

                        <p class="card-title">The restaurant suggested by {{ score|floatformat }}% accuracy!</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-md-center">
            <canvas id="myChart" height="20vh" width="40vw"></canvas>
        </div>
    </div>

{% endif %}

templates/common/base_generic.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}<title>Foodmates</title>{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content=""/>

    <link href="https://png.icons8.com/nolan/50/000000/hamburger.png" rel="icon" type="image/x-icon"/>

    <!-- Animate.css -->
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Damion" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Flexslider  -->
    <!-- Flaticons  -->
    <!-- Owl Carousel -->
    <!-- Theme style  -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">


    <!-- Modernizr JS -->

</head>
<body>
<div id="page" class="shadow-lg">
        <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
            <a class="navbar-brand" href="{% url 'common:index' %}"><span style="font-family: 'Damion', cursive;"><img  src="{% static 'images/lfr.png' %}" /></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                    aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


            <div class="collapse navbar-collapse justify-content-end" id="navbarColor02">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'common:index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'common:places' %}">Restaurants</a>
                    </li>

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:profile' %}">Profile</a>
                        </li>
                        <form style="margin-top: 8px; margin-left: 4px">
                            <input value="Suggest a Place" type="button" class="btn btn-warning outline btn-sm"
                                   onclick="window.location.href='{% url 'common:suggest-place' %}'"/>
                        </form>

                        <form style="margin-left: 10px; margin-top: 7px;">
                            <input value="Logout" type="button" class="btn btn-outline-dark btn-sm"
                                   onclick="window.location.href='{% url 'logout' %}'"/>
                        </form>
                    {% else %}
                        <li class="nav-item"><a class="nav-link"
                                                href="{% url 'login' %}?next={{ request.path }}">Login</a></li>


                    {% endif %}
                </ul>

                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-secondary btn-sm my-2 my-sm-0" type="submit">Search</button>
                </form>


            </div>
        </nav>
    {% block content %} {% endblock %}
</div>

<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>


<!-- MAIN JS -->
<script src="{% static 'js/main.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
<script src="{% static 'js/noframework.waypoints.min.js' %}"></script>


</body>
</html>

templates/common/index.html
{% extends "common/base_generic.html" %}

{% block title %}<title>Home - Foodmates</title>{% endblock %}

{% block content %}

    <header>
        <div class="cover">
            <div class="row text-center">


                <div class="col-sm-12">
                    <a href="{% url 'common:index' %}">
                        {#                    <button type="button" class="btn btn-outline-dark btn-lg">TELL ME MORE</button>#}
                    </a>
                </div>
            </div>
        </div>
    </header>


    <div class="content">
        <div class="jumbotron">
            <div class="jumbotron shadow-sm" style="padding-top: -40px; background: whitesmoke">
                {% if user.is_authenticated %}
                    <h1 class="display-3">Hello, {{ user.get_full_name }}!</h1>
                {% else %}
                    <h1 class="display-3">Welcome to the Foodmates!</h1>

                {% endif %}
                <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra
                    attention to featured content or information.</p>
                <hr class="my-4">
                <p>It uses utility classes for typography and spacing to space content out within the larger
                    container.</p>
                <p class="lead">
                    {% if user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'common:places' %}"
                           role="button">Explore Now!</a>
                        <a class="btn btn-outline-warning" href="{% url 'common:suggest-place' %}"
                           role="button">Try the Foodmates</a>

                    {% else %}
                        <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{ request.path }}"
                           role="button">Login</a>

                    {% endif %}
                </p>
            </div>

            <hr class="my-4">

            <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="card border-light mb-3" style="max-width: 90em">
                            <div class="card-header">Dynamic Content</div>
                            <div class="card-body">
                                <h4 class="card-title">The database has the following record counts:</h4>
                                <p class="card-text">
                                    <strong>Places:</strong> {{ num_places }}
                                    <strong>Users:</strong> {{ num_users }}</p>
                            </div>
                        </div>
                        <p>You have visited this page
                            {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/common/place_detail.html
{% extends "common/base_generic.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>{{ place.title }} - Foodmates</title>{% endblock %}

{% block content %}
    <h1 class="page-title text-center">{{ place.title }} </h1>

    <div class="container-fluid place-detail card">

        <div class="row">
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Average rate: {{ place.rate|floatformat }}</h5>
                    <h6 class="card-subtitle text-muted"><i style="color: darkgrey">{{ place.place_votes.count }}
                        votes</i>
                    </h6>
                    <br/>
                    <p><b>Description: </b></p>{{ place.description }}

                    <form action="{% url 'common:place-detail' place.pk %}" method="post">
                        {% csrf_token %}

                        {{ condition_form.as_p }}

                        <div class="row" style="margin: 5px">{{ vote_form }} <input
                                style="margin: 10px" class="btn btn-outline-warning  btn-sm" type="submit" value="Submit"></div>


                    </form>
                </div>
            </div>

            <div class="place-photo-div col-md-4">
                <img src="{% static 'images/place_photo.jpeg' %}" style="margin-top: 15px; width: 100%; height: 60%"
                     alt="Card image">

            </div>
        </div>

        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">User</th>
                <th scope="col">Datetime</th>
                <th scope="col">Rate</th>
            </tr>
            </thead>
            <tbody>
            {% for vote in place.place_votes.all %}
                <tr>
                    <th scope="row">{{ vote.profile.user.first_name }}</th>
                    <td>{{ vote.vote_datetime }}</td>
                    <td><span class="badge badge-primary badge-pill">{{ vote.rate }}</span></td>
                </tr>
            {% endfor %}


            </tbody>
        </table>

    </div>
    {#  <div style="margin-left:20px;margin-top:20px">#}
    {#    <h4>Copies</h4>#}
    {##}
    {#    {% for copy in book.bookinstance_set.all %}#}
    {#    <hr>#}
    {#    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>#}
    {#    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}#}
    {#    <p><strong>Imprint:</strong> {{copy.imprint}}</p>#}
    {#    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>#}
    {#    {% endfor %}#}
    {#  </div> #}
{% endblock %}

templates/common/place_list.html
{% extends "common/base_generic.html" %}
{% load static %}

{% block title %}<title>Restaurants - Foodmates</title>{% endblock %}


{% block content %}
    <div class="place_list" style="margin: auto;">
        <div class="page-title text-center"><h1>Restaurants</h1></div>
        {% if place_list %}
            <div class="list-group shadow-sm">
                {% for place in place_list %}
                    <a href="{{ place.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start place-item">

                        <div class="row place-title-rank" style="margin: auto;">

                            <div class="icon-box">
                                <img class="shadow-sm" src="{% static 'images/place_icon.png' %}"/>
                            </div>

                            <div class="col-md-11">
                                <div class="d-lg-flex shadow-lg justify-content-between">
                                    <h3 class="mb-1">{{ place.title }}</h3>
                                    <div class="place-rate"><small>{{ place.rate|floatformat }}</small></div>
                                </div>
                                <small>Donec id elit non mi porta.</small>
                            </div>
                        </div>
                    </a>
                {% endfor %}
                {% else %}
                <p>There are no place in the database.</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/common/vote_place.html
{% extends "common/base_generic.html" %}
{% block content %}

    ddd

{% endblock %}